name: scrapbuddy
description: AI-powered waste classification and recycling assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # Core dependencies
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  path_provider: ^2.1.1

  
  # UI dependencies
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  
  # Offline classification
  tflite_flutter: ^0.10.3
  image: ^4.1.7
  
  # Icons
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  google_sign_in: ^6.2.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/localization/
    - assets/images/
    - assets/icons/
    - assets/tflite/
    - assets/tflite/model_unquant.tflite
    - assets/tflite/labels.txt
    - assets/audio/hi/
    - assets/audio/ta/
    - assets/audio/te/
