name: scrapbuddy
description: AI-powered waste classification and recycling assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Core dependencies
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  path_provider: ^2.1.1

  
  # UI dependencies
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/localization/
    - assets/images/
    - assets/icons/
